// 应用级国际化语言包

const languages = {
  'zh-CN': {
    // 通用
    confirm: '确定',
    cancel: '取消',
    save: '保存',
    loading: '加载中...',

    // 登入相關
    loginRequired: '需要登录',
    loginRequiredContent: '请先登录后再使用此功能',
    loginRequiredHistoryDesc: '登录后可查看您的照片生成记录',
    goLogin: '去登录',
    loginLater: '稍后再说',
    wechatLogin: '微信登录',
    loginTips: '登录后可使用完整功能',
    loginConfirmBtn: '确认登录',
    loginNotNow: '暂不登录',
    loginSuccess: '登录成功',
    loginFailed: '登录失败',
    exitConfirmTitle: '提示',
    exitConfirmContent: '不登录将无法使用小程序，确定要退出吗？',
    exitConfirmBtn: '退出',
    goLoginBtn: '去登录',
    back: '返回',
    pleaseCheckAgreement: '请先勾选同意协议',
    pleaseCloseManually: '请手动关闭小程序',
    guestMode: '先逛逛',
    loginAgree: '登录即表示同意',
    userAgreement: '用户协议',
    and: '和',

    // 隐私政策弹窗
    privacyTitle: '用户隐私保护提示',
    privacyContent: '感谢您使用醒美闪图！为了更好地为您提供服务，我们需要您阅读并同意以下协议。我们将严格保护您的个人信息安全，不会向第三方泄露您的隐私数据。',
    disagree: '不同意',
    agreeAndContinue: '同意并继续',
    tip: '提示',
    privacyRejectTip: '拒绝隐私政策将无法使用小程序，确定要退出吗？',
    exitApp: '退出',
    thinkAgain: '再想想',
    privacyConfirmed: '已确认',

    // TabBar
    tabHome: '首页',
    tabHistory: '历史',
    tabMine: '我的',

    // 首页
    appName: '醒美闪图',
    appSlogan: '一键上传，秒出好照片',
    selectScene: '选择场景',
    moreScene: '更多场景',
    moreSceneDesc: '更多精彩场景，敬请期待...',
    comingSoon: '即将上线',

    // 我的页面
    mine_pageTitle: '我的',
    loginRegister: '登录 / 注册',
    clickToLogin: '点击登录',
    loginToGetMore: '登录后享受更多功能',
    loginSuccess: '登录成功',
    logout: '退出',
    logoutTitle: '退出登录',
    logoutConfirm: '确定要退出当前账号吗？',
    logoutSuccess: '已退出登录',
    bindEmail: '绑定邮箱',
    inviteGift: '邀请有礼',
    inviteGiftDesc: '邀1人注册得20醒币',
    myPoints: '我的醒币',
    pointsDetail: '明细',
    recharge: '充值',
    freeGet: '免费获取',
    tipTitle: '提示',
    confirm: '知道了',
    myOrders: '我的订单',
    myOrdersDesc: '快去制作吧',
    couponCenter: '优惠券中心',
    couponAvailable: '张可用',
    inviteFriends: '邀请好友',
    feedback: '意见反馈',
    aboutUs: '关于我们',
    aboutUsTitle: '关于醒美闪图',
    language: '语言 / Language',
    privacyPolicy: '隐私政策',
    confirmed: '已签订',
    version: '醒美闪图 v1.1.0',

    // 意见反馈
    fb_pageTitle: '意见反馈',
    fb_historyTitle: '我的反馈历史',
    fb_addNew: '新建反馈',
    fb_noRecord: '暂无反馈记录',
    fb_noRecordTip: '快来创建您的第一条反馈吧！',
    fb_submitNow: '立即反馈',
    fb_pending: '处理中',
    fb_replied: '已回复',
    fb_edit: '编辑',
    fb_delete: '删除',
    fb_adminReply: '管理员回复：',
    fb_reward: '醒币',
    fb_submitTitle: '提交反馈',
    fb_placeholder: '请详细描述您的问题或建议...',
    fb_addImage: '添加图片',
    fb_submit: '提交',
    fb_submitting: '提交中...',
    fb_submitSuccess: '反馈提交成功',
    fb_submitFailed: '提交失败，请重试',
    fb_deleteConfirm: '确定删除这条反馈吗？',
    fb_deleteSuccess: '删除成功',
    fb_deleteFailed: '删除失败',
    
    // 反馈提交页面
    editFeedback: '编辑反馈',
    submitNewFeedback: '提交新反馈',
    feedbackPlaceholder: '请详细描述您的问题或建议...',
    uploadImageOptional: '上传图片 (可选)',
    contactOptional: '联系方式 (可选)',
    contactPlaceholder: '邮箱或手机号',
    confirmEdit: '确认修改',
    submitFeedback: '提交反馈',

    // 弹窗
    setNickname: '设置昵称',
    enterNickname: '请输入昵称',
    nicknameSaved: '昵称已保存',
    bindEmailTitle: '绑定邮箱',
    enterEmail: '请输入邮箱地址',
    verifyCode: '验证码',
    sendCode: '发送验证码',
    confirmBind: '确认绑定',
    emailBound: '邮箱绑定成功',
    invalidEmail: '邮箱格式不正确',
    codeError: '验证码错误',
    codeSent: '验证码已发送',

    // 语言选择
    selectLanguage: '选择语言 / Language',
    langZhCN: '简体中文',
    langEn: 'English',
    languageChanged: '语言已切换',

    // 历史记录
    generatingPhotos: '张照片生成中...',
    allCompleted: '全部完成',
    historyTitle: '我的照片',
    noHistory: '暂无照片记录',
    goCreate: '去制作',
    generating: '生成中',
    failed: '生成失败',
    retry: '重试',
    download: '下载',
    delete: '删除',
    selectAll: '全选',
    batchDelete: '批量删除',
    selected: '已选',
    items: '项',
    // 历史页面详细
    hist_pageTitle: '生成历史',
    hist_pending: '进行中',
    hist_taskCount: '个任务',
    hist_idPhoto: '证件照',
    // 历史页面筛选标签
    hist_filterStatus: '状态',
    hist_filterSource: '来源',
    hist_filterType: '类型',
    hist_statusAll: '全部',
    hist_statusPending: '进行中',
    hist_statusDone: '已完成',
    hist_statusFailed: '失败',
    hist_sourceAll: '全部',
    hist_sourceOriginal: '原创',
    hist_sourceRemake: '重制',
    hist_filterAll: '全部',
    hist_filterIdPhoto: '证件照',
    hist_filterOther: '其他',
    // 历史页面 - 场景类别名称（用于筛选标签）
    hist_sceneIdPhoto: '证件照',
    hist_sceneProfessional: '职业照',
    hist_scenePortrait: '写真',
    hist_sceneFamily: '全家福',
    hist_scenePet: '宠物照',
    hist_sceneWedding: '婚纱照',
    hist_filterNoRecords: '该分类下暂无记录',
    hist_viewAll: '查看全部',
    hist_aiGenerating: 'AI生成中...',
    hist_failedTitle: '生成失败',
    hist_clearAll: '清除全部',
    hist_photos: '张照片',
    hist_cancel: '取消',
    hist_select: '选择',
    hist_selectedCount: '已选',
    hist_unit: '张',
    hist_email: '邮箱',
    hist_download: '下载',
    hist_delete: '删除',
    hist_noRecords: '暂无生成记录',
    hist_noRecordsTip: '去首页制作你的第一张证件照吧',
    hist_createNow: '立即制作',
    hist_bindEmail: '绑定邮箱',
    hist_bindEmailTip: '绑定邮箱后即可发送照片到邮箱',
    hist_enterEmail: '请输入邮箱地址',
    hist_verifyCode: '验证码',
    hist_sendCode: '发送验证码',
    hist_confirmBindSend: '确认绑定并发送',
    hist_selectPhoto: '请先选择照片',
    hist_sending: '发送中...',
    hist_sentToEmail: '已发送到邮箱',
    hist_saving: '保存中...',
    hist_savedPhotos: '已保存',
    hist_successCount: '成功',
    hist_failCount: '失败',
    hist_confirmDeleteTitle: '确认删除',
    hist_confirmDeletePhotos: '确定要删除选中的',
    hist_confirmDeleteSuffix: '张照片吗？',
    hist_deleted: '删除成功',
    hist_clearFailedTitle: '清除失败任务',
    hist_clearFailedContent: '确定清除全部',
    hist_clearFailedSuffix: '个失败任务吗？',
    hist_cleared: '已清除',
    hist_confirmDeleteOne: '删除后无法恢复，确定要删除吗？',
    hist_justNow: '刚刚',
    hist_minutesAgo: '分钟前',
    hist_hoursAgo: '小时前',
    hist_daysAgo: '天前',
    hist_month: '月',
    hist_day: '日',
    hist_needAlbum: '需要授权保存相册权限',
    hist_saveFailed: '保存失败',
    hist_savedToAlbum: '已保存到相册',
    hist_aiDisclaimer: '以下图像均由AI生成，仅供参考，请谨慎甄别',
    hist_freeRetry: '可免费重拍1次',
    hist_freeRetryTitle: '免费重新生成',
    hist_freeRetryConfirm: '您有1次免费重新生成的机会，是否使用？',
    hist_retrying: '重新生成中...',
    hist_retryStarted: '已开始重新生成',
    hist_retrySuccess: '重新生成已加入队列',
    hist_noRetryLeft: '免费重拍次数已用完',
    hist_imageNotFound: '原图已失效，无法重拍',
    hist_cancelTaskTitle: '取消任务',
    hist_cancelTaskContent: '确定要取消这个生成任务吗？',
    hist_cancelTaskContentWithWarning: '确定要取消这个生成任务吗？\n\n注意：用户主动取消的任务，已消耗的醒币将不予退还。',
    hist_taskCanceled: '已取消',
    hist_timeoutError: '生成超时，请重试',
    hist_retryTitle: '重新生成',
    hist_retryConfirm: '是否使用原配置重新生成照片？',
    hist_systemErrorRetryTitle: '免费重新生成',
    hist_systemErrorRetryConfirm: '因系统原因生成失败，本次不消耗醒币，是否使用原图片和参数重新生成？',
    hist_noPrompt: '无法重制：缺少原始配置',
    // 分享功能
    hist_sharePoster: '分享海报',
    hist_shareCouponTip: '首次分享可获得10醒币',
    hist_shareToFriend: '分享给好友',
    hist_savePoster: '保存海报',
    hist_shareCouponName: '分享奖励',
    hist_couponGrantedTitle: '恭喜获得醒币',
    hist_couponGrantedContent: '您已获得10醒币奖励！',
    hist_posterShareTitle: '我用醒美闪图生成了一张照片，效果超赞！',
    hist_posterDesc: '专业AI生图，一键生成',
    hist_posterTip: '长按识别，立即体验',
    hist_tryNow: '立即体验',
    // 详情弹窗操作按钮
    detail_share: '分享',
    detail_remake: '重制',
    detail_save: '保存',
    detail_delete: '删除',
    // 详情弹窗生成条件标题
    detail_conditions: '生成条件',

    // 隐私政策提示
    privacyTip: '为保障你的权益，请先阅读并同意隐私政策后再使用上传、生成、支付等功能。',
    viewAndAgree: '查看并同意',
    notNow: '暂不',

    // 关于我们页面
    about_pageTitle: '关于我们',
    about_appName: '醒美闪图',
    about_slogan: '一键上传，秒出好照片',
    about_intro_title: '产品介绍',
    about_intro_content: '醒美闪图是一款基于先进AI技术的智能照片生成工具。我们致力于为用户提供便捷、高质量的照片制作服务，支持证件照、写真照、全家福、宠物写真、婚纱照等多种场景，让您足不出户即可获得专业级别的精美照片。',
    about_features_title: '核心功能',
    about_feature1_name: 'AI智能美颜',
    about_feature1_desc: '智能优化肤色、自然磨皮、去除瑕疵，呈现最美的你',
    about_feature2_name: '多种场景',
    about_feature2_desc: '证件照、写真照、全家福、宠物写真、婚纱照等丰富场景',
    about_feature3_name: '专业规格',
    about_feature3_desc: '一寸、二寸、签证照等多种尺寸，满足各类证件需求',
    about_feature4_name: '智能换装',
    about_feature4_desc: '海量服装模板，一键更换专业着装或时尚穿搭',
    about_contact_title: '联系我们',
    about_email: '客服邮箱',
    about_contact_tips: '如有任何问题或建议，欢迎通过邮箱与我们联系，我们将在24小时内回复您。',
    about_copyright: '© 2026 上海醒美元子网络科技工作室（个人独资）所有',
    about_share_title: '醒美闪图 - AI智能照片生成',
    copied: '已复制',
    aboutContent: '醒美闪图是一款专业的AI照片生成工具，支持证件照、写真照、全家福等多种类型，提供智能美颜、换装等功能。',

    // 功能开发中
    featureInDev: '功能开发中',

    // 头像和昵称
    avatarUpdated: '头像已更新',
    pleaseEnterNickname: '请输入昵称',
    nicknameSaved: '昵称已保存',

    // 邮箱绑定
    pleaseEnterEmail: '请输入邮箱地址',
    emailFormatError: '邮箱格式不正确',
    sending: '发送中...',
    codeSent: '验证码已发送',
    testTip: '测试提示',
    testCodeContent: '验证码为：{code}（正式环境会发送到邮箱）',
    pleaseEnterCode: '请输入验证码',
    codeError: '验证码错误',
    emailBindSuccess: '邮箱绑定成功',

    // 分享
    shareTitle: '醒美闪图 - 专业证件照，一键生成',
    historyShareTitle: '我用醒美闪图制作了一张证件照，效果太棒了！',
    newUserWelcome: '欢迎新用户！首单立减¥5',

    // 充值页面
    recharge_title: '充值醒币',
    currentPoints: '当前醒币',
    selectPackage: '选择充值金额',
    pointsUnit: '醒币',
    customAmount: '自定义金额',
    enterAmount: '输入金额（1-10000整数）',
    rechargeTips: '充值说明',
    rechargeTip1: '1元 = 10醒币',
    rechargeTip2: '充值金额越大，赠送醒币越多',
    rechargeTip3: '醒币可用于购买小程序内所有服务',
    rechargeTip4: '充值成功后立即到账',
    payAmount: '支付金额',
    rechargeNow: '立即充值',
    processing: '处理中...',
    pleaseEnterValidAmount: '请输入有效金额',
    pleaseSelectAmount: '请选择充值金额',
    testMode: '测试模式',
    testRechargeConfirm: '模拟充值 ¥{amount}，获得 {points} 醒币？',
    rechargeSuccess: '充值成功',
    rechargeFailed: '充值失败',
    paymentCancelled: '已取消支付',
    paymentFailed: '支付失败',
    pleaseLogin: '请先登录',
    iosPaymentNotice: 'iOS虚拟支付暂未开放',
    iosPaymentDesc: '您可以通过以下方式获取醒币：',
    iosPaymentTip1: '使用安卓设备充值',
    iosPaymentTip2: '分享小程序给好友',
    iosPaymentTip3: '邀请好友注册获得奖励',
    iosPaymentModalContent: '请使用安卓设备充值，或通过分享、邀请好友等方式获取醒币',
    iKnow: '我知道了',

    // 醒币明细页面
    pointsRecord_title: '醒币明细',
    pointsHistory: '醒币记录',
    noRecords: '暂无醒币记录',
    pr_balance: '余额',
    pr_noMore: '没有更多了',
    pr_loadFailed: '加载失败',
    pr_newUser: '新用户奖励',
    pr_shareImage: '分享图片奖励',
    pr_inviteFriend: '邀请好友奖励',
    pr_recharge: '充值',
    pr_testRecharge: '测试充值',
    pr_virtualRecharge: '虚拟充值',
    pr_consume: '消费',
    pr_adminAdjust: '系统调整',
    pr_refund: '系统退还',
    pr_generate: '生成照片',
    pr_systemGrant: '系统发放',
    pr_activityReward: '活动奖励',

    // 证件照页面
    fp_uploadPhoto: '上传照片',
    fp_uploadTip: '最多3张，AI参考生成',
    fp_add: '添加',
    fp_photoSpec: '照片规格',
    fp_oneInch: '一寸',
    fp_twoInch: '二寸',
    fp_smallOneInch: '小一寸',
    fp_bigOneInch: '大一寸',
    fp_beauty: '美颜修饰',
    fp_beautyNone: '原图直出',
    fp_beautyNoneDesc: '只做裁剪换底',
    fp_beautyNatural: '自然美化',
    fp_beautyNaturalDesc: '轻微磨皮祛痘',
    fp_beautyEnhanced: '精致修图',
    fp_beautyEnhancedDesc: '瘦脸提亮',
    fp_recommend: '推荐',
    fp_smartClothing: '智能换装',
    fp_male: '男士',
    fp_female: '女士',
    fp_noClothing: '不换装',
    fp_suitTie: '西装领带',
    fp_suit: '西装',
    fp_whiteShirt: '白衬衫',
    fp_vNeck: 'V领',
    fp_roundNeck: '圆领',
    fp_shirt: '衬衫',
    fp_bgColor: '背景颜色',
    fp_white: '白底',
    fp_blue: '蓝底',
    fp_darkBlue: '深蓝',
    fp_red: '红底',
    fp_gray: '灰底',
    fp_darkGray: '深灰',
    fp_gradient: '渐变',
    fp_beige: '米色',
    fp_lightGreen: '浅绿',
    fp_brown: '棕褐',
    fp_unit: '张',
    fp_generateNow: '立即生成',
    fp_confirmPay: '确认支付',
    fp_generateQty: '生成数量',
    fp_unitPrice: '单价',
    fp_perPhoto: '/张',
    fp_subtotal: '小计',
    fp_coupon: '优惠券',
    fp_available: '张可用',
    fp_noCoupon: '不使用优惠券',
    fp_tips: '温馨提示',
    fp_disclaimer: '本服务为 AI 实时生成服务，确认支付后将立即消耗算力完成生成。因服务已即时履约，生成完成后暂不支持退款。请在确认支付前检查照片与参数设置。',
    fp_shouldPay: '应付：',
    fp_saved: '已优惠',
    fp_confirmPayBtn: '确认支付',
    fp_pleaseUpload: '请先上传照片',
    fp_addedToQueue: '已加入生成队列',
    fp_photosGenerating: '张照片生成中...',
    fp_reassurance: '可自由切换页面，不影响生成',
    fp_completedTapToView: '全部完成！点击查看结果',
    fp_photosCompleted: '张照片已生成完成',
    fp_generateComplete: '张证件照生成完成，去历史页面查看',
    fp_generateFailed: '生成失败，请重试',
    fp_confirmDelete: '确认删除',
    fp_confirmDeleteContent: '确定要删除这条记录吗？',
    fp_filteredFormats: '已过滤不支持的格式（仅支持JPG/PNG）',
    fp_sensitiveContent: '图片内容不符合要求',
    fp_sensitiveContentModal: '您上传的图片内容不符合证件照要求（可能包含敏感内容），请更换照片后重试。本次未产生扣费。',
    fp_iKnow: '我知道了',
    fp_noImage: '未获取到图片',
    fp_privacyModalTitle: '请先确认隐私政策',
    fp_privacyModalContent: '在使用支付功能前，您需要阅读并同意我们的隐私政策。本小程序仅在用户主动操作时获取必要信息，用于证件照生成服务。',
    fp_viewPrivacy: '查看《隐私政策》完整内容',
    fp_agreeAndContinue: '同意并继续',
    fp_privacyRequired: '请先同意隐私政策后再使用此功能',
    fp_goAgree: '去同意',
    fp_noCouponAvailable: '暂无可用优惠券',
    fp_needAlbumPermission: '需要授权保存相册权限',
    fp_savedCount: '成功保存',
    fp_saveFailed: '保存失败',
    fp_sceneResume: '证件照',
    fp_scenePassport: '签证证件照',
    fp_sceneExam: '考试证件照',
    fp_sceneSocial: '社保证件照',
    fp_sceneStudent: '学生证件照',

    // 场景页面额外翻译
    missingSceneParam: '缺少场景参数',
    sceneNotExist: '场景不存在',
    configLoadFailed: '配置加载失败',
    checkingImage: '正在检测图片...',
    pleaseAgreePrivacy: '请先同意协议',
    pleaseCompleteAction: '请先完成操作',
    scene: '场景',
    photo: '照片',
    userNotLoggedIn: '用户未登录',
    deductFailed: '扣费失败',
    noAvailableImage: '没有可用的图片',
    cannotReadImage: '无法读取图片',
    downloadFailed: '下载失败',
    points: '醒币',
    consumePoints: '消耗醒币',
    currentBalance: '当前余额',
    insufficientBalance: '余额不足，请先充值',
    iosInsufficientBalance: '余额不足，可通过邀请好友、分享照片等方式获取醒币',
    goRecharge: '去充值',
    hist_generateComplete: '生成完成，点击查看',
    balanceAfterPay: '支付后余额',
    noMore: '没有更多了',
    invalidPath: '路径不正确',
    hist_sharePointsTip: '首次分享可获得10醒币',
    hist_pointsGrantedTitle: '恭喜获得醒币',
    hist_pointsGrantedContent: '您已获得{points}醒币奖励',
    hist_remakeTag: '重制',

    // 职业照页面
    pp_pageTitle: '职业照',
    pp_uploadPhoto: '上传生活照',
    pp_uploadTip: '最多3张，AI参考生成',
    pp_gender: '选择性别',
    pp_industry: '选择行业',
    pp_posture: '选择姿势',
    pp_indTech: '科技互联网',
    pp_indFinance: '金融投资',
    pp_indEducation: '教育培训',
    pp_indMedical: '医疗健康',
    pp_indCreative: '创意设计',
    pp_indLegal: '法律服务',
    pp_indMarketing: '市场营销',
    pp_indMedia: '媒体传播',
    pp_indAdmin: '行政管理',
    pp_indOther: '其他行业',
    pp_profession: '选择职业',
    // 科技互联网职业
    pp_profSoftwareEngineer: '软件工程师',
    pp_profProductManager: '产品经理',
    pp_profUIDesigner: 'UI设计师',
    pp_profDataAnalyst: '数据分析师',
    pp_profProjectManager: '项目经理',
    // 金融行业职业
    pp_profBanker: '银行从业者',
    pp_profInvestAdvisor: '投资顾问',
    pp_profAccountant: '会计师',
    pp_profInsurance: '保险顾问',
    pp_profSecurities: '证券从业者',
    // 教育培训职业
    pp_profTeacher: '教师',
    pp_profProfessor: '教授',
    pp_profTrainer: '培训师',
    pp_profCounselor: '教育咨询师',
    // 医疗健康职业
    pp_profDoctor: '医生',
    pp_profNurse: '护士',
    pp_profPharmacist: '药剂师',
    pp_profTherapist: '康复治疗师',
    // 法律服务职业
    pp_profLawyer: '律师',
    pp_profLegalConsultant: '法务顾问',
    pp_profNotary: '公证员',
    // 市场营销职业
    pp_profMarketingManager: '市场经理',
    pp_profSalesManager: '销售经理',
    pp_profBrandPlanner: '品牌策划',
    pp_profPR: '公关专员',
    // 媒体传播职业
    pp_profJournalist: '记者',
    pp_profEditor: '编辑',
    pp_profHost: '主持人',
    pp_profVideoProducer: '视频制作人',
    // 行政管理职业
    pp_profHR: '人力资源经理',
    pp_profAdminManager: '行政经理',
    pp_profExecutive: '企业高管',
    pp_profSecretary: '秘书助理',
    // 其他职业
    pp_profEntrepreneur: '创业者',
    pp_profFreelancer: '自由职业者',
    pp_profConsultant: '咨询顾问',
    pp_profGeneral: '职场人士',
    pp_profOther: '其他',
    pp_generateComplete: '张职业照生成完成',
    pp_desc: '求职主页、名片社交、职业形象',
    professionalPhoto: '职业照',
    pp_darkBlue: '深蓝',
    pp_darkGray: '深灰',
    pp_beige: '米色',
    pp_lightGreen: '浅绿',
    pp_brown: '棕褐',
    pp_framing: '构图',
    pp_framingCloseup: '头肩特写',
    pp_framingHalfbody: '标准半身',
    pp_framingThreequarter: '四分三身',
    pp_framingFullbody: '全身照',

    // 订单页面
    order_pageTitle: '订单记录',
    order_title: '我的订单',
    order_id: '订单号',
    order_generateQty: '生成数量',
    order_coupon: '优惠券',
    order_actualPay: '实付',
    order_completed: '已完成',
    order_pending: '处理中',
    order_failed: '已失败',
    order_noOrders: '暂无订单记录',
    order_goPhoto: '去拍照',

    // 优惠券页面
    coupon_pageTitle: '我的优惠券',
    coupon_newUser: '新人专享券',
    coupon_noThreshold: '无门槛',
    coupon_available: '可使用',
    coupon_used: '已使用',
    coupon_expired: '已过期',
    coupon_noAvailable: '暂无可用优惠券',
    coupon_noUsed: '暂无已使用优惠券',
    coupon_noExpired: '暂无已过期优惠券',
    coupon_useNow: '立即使用',
    coupon_inviteToGet: '邀请好友得优惠券',
    coupon_validUntil: '有效期至',
    coupon_longTerm: '长期有效',

    // 邀请页面
    invite_pageTitle: '邀请好友',
    invite_title: '邀请好友 一起省钱',
    invite_desc: '每邀请1位好友，双方各得20醒币',
    invite_invited: '已邀请(人)',
    invite_earned: '已获得(张)',
    invite_earnedPoints: '获得醒币',
    invite_claimable: '可领取(张)',
    invite_pending: '待领取',
    invite_nextProgress: '下一张券进度',
    invite_person: '第',
    invite_personUnit: '位',
    invite_getCoupon: '得券',
    invite_pendingClaim: '张优惠券待领取',
    invite_claimNow: '立即领取',
    invite_claimedCount: '已领取',
    invite_continueInvite: '张优惠券，继续邀请可获得更多',
    invite_moreToGet: '再邀请',
    invite_personToGet: '位好友即可获得1张优惠券',
    invite_method: '邀请方式',
    invite_step1: '分享小程序',
    invite_step1Desc: '发送给好友',
    invite_step2: '好友点击',
    invite_step2Desc: '进入小程序',
    invite_step3: '完成注册',
    invite_step3Desc: '双方获得奖励',
    invite_shareTip: '点击右上角「...」分享给好友同样有效',
    invite_shareMiniProgram: '分享小程序',
    invite_sendToFriend: '发送给好友',
    invite_friendClick: '好友点击',
    invite_enterMiniProgram: '进入小程序',
    invite_generatePhoto: '同意隐私政策',
    invite_success: '邀请成功',
    invite_shareNow: '立即分享给好友',
    invite_rules: '活动规则',
    invite_rule1: '邀请好友通过您的链接进入小程序',
    invite_rule2: '好友注册并同意隐私政策即算邀请成功',
    invite_rule3: '每成功邀请1位好友，双方各获得20醒币',
    invite_rule4: '醒币可用于小程序内所有服务消费',
    invite_records: '邀请记录',
    invite_friend: '好友',
    invite_shareTitle: '我在用醒美闪图，AI出图超好用！好友注册即可得醒币！',
    share_text: '我在用醒美闪图，AI出图超好用！好友注册即可得醒币！',
    invite_noCouponToClaim: '暂无可领取的优惠券',
    invite_couponClaimed: '张优惠券已到账',
    invite_rewardCoupon: '邀请好友奖励券',
    invite_noThreshold: '无门槛',
    invite_rewardTitle: '奖励说明',
    invite_friendReward: '邀请好友注册',
    invite_friendRewardDesc: '好友完成注册，双方各得',
    invite_shareReward: '分享生成的照片',
    invite_shareRewardDesc: '首次分享海报，每日无上限！',

    // 隐私政策页面
    privacy_pageTitle: '隐私政策',
    privacy_title: '隐私政策',
    privacy_welcome: '欢迎使用醒美闪图(以下简称"我们")。',
    privacy_intro: '我们非常重视用户的个人信息与隐私保护。本隐私政策将向您说明,在您使用本小程序服务过程中,我们如何收集、使用、存储和保护您的个人信息,以及您享有的相关权利。',
    privacy_read_tip: '请您在使用本小程序前,仔细阅读并理解本隐私政策。',
    privacy_section1_title: '一、我们如何收集和使用您的个人信息',
    privacy_section1_intro: '我们仅会出于以下合法、正当、必要的目的,收集和使用您的个人信息。',
    privacy_s1_1_title: '1. 注册与登录',
    privacy_s1_1_desc: '当您使用微信授权登录本小程序时,我们将收集以下信息:',
    privacy_s1_1_item1: '微信用户唯一标识(openid)',
    privacy_s1_1_item2: 'unionid(如微信提供)',
    privacy_s1_1_purpose: '使用目的:用于用户身份识别、账号创建与登录。',
    privacy_s1_1_note: '我们不会要求您提供手机号、身份证号等额外信息。',
    privacy_s1_2_title: '2. 证件照生成与编辑服务',
    privacy_s1_2_desc: '当您使用证件照生成相关功能时,我们将收集:',
    privacy_s1_2_item1: '您主动上传的照片原图',
    privacy_s1_2_item2: '生成后的证件照图片',
    privacy_s1_2_purpose: '使用目的:用于完成您请求的AI证件照生成、预览、下载等功能。',
    privacy_s1_2_note: '您的照片仅用于本次服务,不会用于广告、营销或模型训练等其他用途。',
    privacy_s1_3_title: '3. 订单与支付',
    privacy_s1_3_desc: '当您进行付费操作时,我们将收集:',
    privacy_s1_3_item1: '订单号',
    privacy_s1_3_item2: '交易金额',
    privacy_s1_3_item3: '支付状态',
    privacy_s1_3_purpose: '使用目的:用于完成支付、订单确认及售后服务。',
    privacy_s1_3_note: '支付过程由微信支付完成,我们不会获取您的银行卡号、密码等敏感信息。',
    privacy_s1_4_title: '4. 客服与意见反馈(如您主动使用)',
    privacy_s1_4_desc: '当您联系客服或提交反馈时,我们可能会收集:',
    privacy_s1_4_item1: '您主动填写的联系方式',
    privacy_s1_4_item2: '反馈内容',
    privacy_s1_4_purpose: '使用目的:用于与您沟通、处理问题与改进服务。',
    privacy_s1_5_title: '5. 系统安全与运行保障',
    privacy_s1_5_desc: '为保障小程序安全运行,我们可能会收集:',
    privacy_s1_5_item1: 'IP地址',
    privacy_s1_5_item2: '设备型号',
    privacy_s1_5_item3: '操作系统版本',
    privacy_s1_5_item4: '基本操作日志',
    privacy_s1_5_purpose: '使用目的:用于安全防护、异常排查及系统稳定性保障。',
    privacy_section2_title: '二、我们如何存储和保护您的个人信息',
    privacy_section2_item1: '我们将在完成服务所需的最短时间内保存您的个人信息。',
    privacy_section2_item2: '超过保存期限后,相关信息将被删除或匿名化处理。',
    privacy_section2_item3: '我们采用合理的技术与管理措施,保护您的信息不被未经授权访问、泄露或滥用。',
    privacy_section3_title: '三、我们如何共享、转让或披露您的个人信息',
    privacy_s3_1_title: '1. 第三方服务说明',
    privacy_s3_1_desc: '为实现相关功能,我们可能会使用以下第三方服务:',
    privacy_s3_1_item1: '微信开放平台:用于微信登录与微信支付',
    privacy_s3_1_item2: '云服务/AI图像处理服务:用于完成证件照生成与图片存储',
    privacy_s3_1_note: '我们仅在实现功能所必需的范围内共享信息。',
    privacy_s3_2_title: '2. 我们不会:',
    privacy_s3_2_item1: '向无关第三方出售您的个人信息',
    privacy_s3_2_item2: '将您的照片用于广告或营销',
    privacy_s3_2_item3: '擅自公开您的个人信息',
    privacy_s3_2_note: '除非法律法规另有规定或获得您的明确同意。',
    privacy_section4_title: '四、您的权利',
    privacy_section4_intro: '您有权:',
    privacy_section4_item1: '查询、更正您的个人信息',
    privacy_section4_item2: '删除您的个人信息(在法律允许范围内)',
    privacy_section4_item3: '撤回授权(可能影响部分功能使用)',
    privacy_section4_contact: '您可通过小程序内的客服入口联系我们。',
    privacy_section5_title: '五、未成年人保护',
    privacy_section5_content: '若您未满14周岁,请在监护人同意和指导下使用本小程序。',
    privacy_section6_title: '六、本政策的更新',
    privacy_section6_content: '我们可能适时对本隐私政策进行更新。更新后将通过小程序内页面进行展示。',
    privacy_section7_title: '七、联系我们',
    privacy_section7_content: '如您对本隐私政策有任何疑问、意见或建议,可通过小程序内客服/反馈入口与我们联系。',
    privacy_checkbox_text: '我已阅读并同意以上隐私政策',
    privacy_confirm_btn: '确认',
    privacy_please_agree: '请先勾选同意',
    privacy_confirmed_toast: '已确认隐私政策',
    privacy_share_title: '醒美闪图 - 隐私政策',

    // 用户协议页面
    terms_pageTitle: '用户协议',
    terms_title: '用户协议',
    terms_welcome: '欢迎您使用醒美闪图（以下简称"本产品"或"我们"）。',
    terms_intro: '请您在使用本产品前，仔细阅读并充分理解本用户协议的全部内容。如您不同意本协议的任何条款，请勿使用本产品。您使用本产品即表示您已阅读并同意本协议。',
    terms_section1_title: '一、服务说明',
    terms_section1_content: '本产品是一款基于人工智能技术的证件照生成工具，为用户提供证件照拍摄、美化、换装、换背景等服务。',
    terms_s1_item1: '用户上传照片后，可选择不同规格、背景颜色、美颜程度等参数',
    terms_s1_item2: 'AI将根据用户选择的参数生成符合要求的证件照',
    terms_s1_item3: '生成的照片可下载保存或发送至邮箱',
    terms_section2_title: '二、用户账号',
    terms_section2_intro: '您可以通过微信授权登录使用本产品。',
    terms_s2_item1: '您应妥善保管账号信息，因您的原因导致账号被盗用或信息泄露，由您自行承担责任',
    terms_s2_item2: '您不得将账号转让、出借给他人使用',
    terms_s2_item3: '如发现账号被他人非法使用，应立即通知我们',
    terms_section3_title: '三、用户行为规范',
    terms_section3_intro: '您在使用本产品时，应遵守以下规范：',
    terms_s3_item1: '不得上传违法、色情、暴力等不良内容的照片',
    terms_s3_item2: '不得上传侵犯他人肖像权、隐私权的照片',
    terms_s3_item3: '不得将生成的照片用于任何非法目的',
    terms_s3_item4: '不得利用本产品从事任何违反法律法规的活动',
    terms_s3_item5: '不得干扰或破坏本产品的正常运行',
    terms_section4_title: '四、醒币规则与付费服务',
    terms_section4_intro: '本产品使用"醒币"作为虚拟服务货币，请仔细阅读以下规则：',
    terms_s4_item1: '醒币是本产品的虚拟服务道具，仅可用于本小程序内的服务消费，不具有货币价值',
    terms_s4_item2: '醒币获取方式：充值购买（1元=10醒币）、邀请好友奖励、分享奖励等',
    terms_s4_item3: '醒币仅限在本小程序内使用，不支持转赠、转让、提现或兑换为现金',
    terms_s4_item4: '因AI实时生成服务的特殊性，醒币一经消费即视为服务已交付，不支持退款',
    terms_s4_item5: '因系统原因导致生成失败的，已消费的醒币将自动退还',
    terms_s4_item6: '用户主动取消正在生成的任务，已消耗的醒币不予退还',
    terms_s4_item7: '账户注销时，账户内剩余醒币将被清零且无法恢复，请在注销前使用完毕',
    terms_s4_item8: '我们有权根据运营需要调整醒币的获取规则和消费价格，调整前将提前通知',
    terms_section5_title: '五、知识产权',
    terms_section5_intro: '关于本产品的知识产权说明：',
    terms_s5_item1: '本产品的所有内容（包括但不限于文字、图片、代码、界面设计等）的知识产权归我们所有',
    terms_s5_item2: '用户上传的原始照片，其知识产权归用户所有',
    terms_s5_item3: 'AI生成的证件照，用户享有使用权，可用于个人合法用途',
    terms_s5_item4: '未经授权，用户不得对本产品进行反向工程、反编译等操作',
    terms_section6_title: '六、免责声明',
    terms_section6_intro: '在法律允许的范围内，我们对以下情况不承担责任：',
    terms_s6_item1: 'AI生成的照片仅供参考，可能与真实照片存在差异',
    terms_s6_item2: '因不可抗力、网络故障等原因导致的服务中断或数据丢失',
    terms_s6_item3: '用户因违反本协议或相关法律法规而产生的任何后果',
    terms_s6_item4: '用户将生成的照片用于特定场景（如签证申请）时，应自行确认是否符合该场景的具体要求',
    terms_section7_title: '七、协议修改',
    terms_section7_content: '我们有权根据需要修改本协议。协议修改后，我们将在产品内公布。如您继续使用本产品，即表示您接受修改后的协议。如您不同意修改后的协议，请停止使用本产品。',
    terms_section8_title: '八、法律适用与争议解决',
    terms_section8_content: '本协议的订立、执行和解释及争议的解决均应适用中华人民共和国法律。如发生争议，双方应友好协商解决；协商不成的，任何一方均可向产品运营方所在地有管辖权的人民法院提起诉讼。',
    terms_section9_title: '九、联系我们',
    terms_section9_content: '如您对本协议有任何疑问，可通过产品内的"意见反馈"功能与我们联系。',
    terms_update_time: '本协议最后更新日期：2025年1月',
    terms_share_title: '醒美闪图 - 用户协议',

    // 新增：用户信息弹窗
    userInfoModal_nicknameRequired: '请输入昵称',
    userInfoModal_setSuccess: '设置成功',
    userInfoModal_setFailed: '设置失败',

    // 新增：反馈提交页面补充
    feedbackSubmit_editTitle: '编辑反馈',
    feedbackSubmit_imageUploadFailed: '图片上传失败',
    feedbackSubmit_contentRequired: '请输入反馈内容',
    feedbackSubmit_sensitiveFiltered: '部分敏感内容已过滤',
    feedbackSubmit_contentReviewing: '内容审核中...',
    feedbackSubmit_imageUploading: '图片正在上传，请稍候',
    feedbackSubmit_editSuccess: '修改成功',
    feedbackSubmit_submitSuccess: '提交成功',

    // 新增：积分记录类型
    pr_type_newUser: '新用户奖励',
    pr_type_shareImage: '分享图片奖励',
    pr_type_inviteFriend: '邀请好友奖励',
    pr_type_recharge: '充值',
    pr_type_testRecharge: '测试充值',
    pr_type_virtualRecharge: '虚拟充值',
    pr_type_consume: '消费',
    pr_type_generatePhoto: '生成照片',
    pr_type_systemAdjust: '系统调整',
    pr_type_systemRefund: '系统退还',
    pr_type_systemGrant: '系统发放',
    pr_type_activityReward: '活动奖励',

    // 新增：我的页面补充
    mine_changeAvatar: '更换头像',
    mine_viewLargeImage: '查看大图',
    mine_uploadingAvatar: '上传头像中...',
    mine_avatarUploadFailed: '头像上传失败',
    mine_avatarUpdated: '头像已更新',
    mine_nicknameUpdated: '昵称已更新',
    mine_nicknameRequired: '请输入昵称',
    mine_saveSuccess: '保存成功',

    // 新增：反馈页面补充
    fb_title: '意见反馈',
    fb_deleteConfirmTitle: '提示',
    fb_deleteConfirmContent: '确定要删除这条反馈吗？',
    fb_deleted: '已删除',
    fb_deleteFailed: '删除失败',

    // 新增：订单页面补充
    order_consumeTitle: '消费记录',
    order_statusCompleted: '已完成',
    order_photoGeneration: '照片生成',
    order_unit: '张',
    order_consume: '消费',
    order_pointsUnit: '醒币',
    order_loadingMore: '加载中...',
    order_noMoreData: '没有更多了',

    // 新增：隐私弹窗补充
    privacyModal_signFailed: '签署失败',
    privacyModal_signFailedMessage: '协议签署失败，请检查网络后重试',

    // 新增：全局提示
    app_networkDisconnected: '网络已断开',
    app_networkRestored: '网络已恢复',

    // 新增：通用
    common_tip: '提示',
    common_networkError: '网络错误',
    common_loadFailed: '加载失败',

    // 场景页面 - 生成进度阶段
    progress_queued: '排队中...',
    progress_deducting: '扣费处理...',
    progress_uploading: '上传图片...',
    progress_processing: 'AI处理中...',
    progress_generating: '生成图片...',
    progress_enhancing: '优化处理...',
    progress_saving: '保存中...',
    progress_done: '完成',
    progress_retrying: '重试中({retry}/3)...',

    // 场景页面 - 余额不足弹窗
    insufficientBalanceTitle: '余额不足',
    needMorePoints: '还需',
    howToEarnPoints: '获取醒币方式：',
    earnTip1: '邀请好友 +50醒币/人',
    earnTip2: '分享照片 +10醒币/次',
    earnTip3: '充值 1元=10醒币',

    // 场景页面 - 生成完成提示
    photosGenerateComplete: '{count}张照片生成完成',

    // 看视频得醒币页面
    videoReward_title: '看视频得醒币',
    videoReward_watch: '观看视频',
    videoReward_watching: '观看中...',
    videoReward_todayEarned: '今日已获得',
    videoReward_perVideo: '每次观看可得',
    videoReward_tips: '观看完整视频即可获得醒币奖励',
    videoReward_success: '恭喜获得',
    videoReward_continue: '继续观看',
    watchVideo: '看视频得醒币',
    watchVideoDesc: '看视频得10醒币',

    // 摇骰子组件
    dice_clickToRoll: '点击骰子抽取',
    dice_rolling: '抽取中...',
    dice_rollAgain: '再摇一次',
    dice_clickRoll: '点击抽取',
    dice_free: '免费',
    dice_confirmTitle: '确认消耗醒币',
    dice_confirmDesc: '本次摇骰子将消耗',
    dice_currentBalance: '当前余额',
    dice_insufficientPoints: '醒币不足'
  },

  'en': {
    // Common
    confirm: 'OK',
    cancel: 'Cancel',
    save: 'Save',
    loading: 'Loading...',

    // Login related
    loginRequired: 'Login Required',
    loginRequiredContent: 'Please login first to use this feature',
    loginRequiredHistoryDesc: 'Login to view your photo generation history',
    goLogin: 'Login',
    loginLater: 'Later',
    wechatLogin: 'WeChat Login',
    loginTips: 'Login for full features',
    loginConfirmBtn: 'Confirm Login',
    loginNotNow: 'Not Now',
    loginSuccess: 'Login Successful',
    loginFailed: 'Login Failed',
    exitConfirmTitle: 'Notice',
    exitConfirmContent: 'You cannot use the app without logging in. Are you sure you want to exit?',
    exitConfirmBtn: 'Exit',
    goLoginBtn: 'Login',
    back: 'Back',
    pleaseCheckAgreement: 'Please check to agree first',
    pleaseCloseManually: 'Please close the app manually',
    guestMode: 'Browse First',
    loginAgree: 'By logging in, you agree to',
    userAgreement: 'Terms of Service',
    and: 'and',

    // Privacy Policy Modal
    privacyTitle: 'Privacy Protection Notice',
    privacyContent: 'Thank you for using FlashPhoto! To better serve you, please read and agree to the following. We strictly protect your personal information and will not share your privacy data with third parties.',
    disagree: 'Disagree',
    agreeAndContinue: 'Agree & Continue',
    tip: 'Notice',
    privacyRejectTip: 'You cannot use the app without agreeing to the privacy policy. Are you sure you want to exit?',
    exitApp: 'Exit',
    thinkAgain: 'Cancel',
    privacyConfirmed: 'Confirmed',

    // TabBar
    tabHome: 'Home',
    tabHistory: 'History',
    tabMine: 'Me',

    // Home
    appName: 'FlashPhoto',
    appSlogan: 'Upload once, get perfect photos instantly',
    selectScene: 'Select Scene',
    moreScene: 'More Scenes',
    moreSceneDesc: 'More exciting scenes coming soon...',
    comingSoon: 'Coming Soon',

    // My Page
    mine_pageTitle: 'Me',
    loginRegister: 'Login / Register',
    clickToLogin: 'Tap to Login',
    loginToGetMore: 'Login for more features',
    loginSuccess: 'Login successful',
    logout: 'Logout',
    logoutTitle: 'Logout',
    logoutConfirm: 'Are you sure you want to logout?',
    logoutSuccess: 'Logged out',
    bindEmail: 'Bind Email',
    inviteGift: 'Invite & Earn',
    inviteGiftDesc: 'Invite 1 friend, get 10 points',
    myPoints: 'My Points',
    pointsDetail: 'Detail',
    recharge: 'Top Up',
    freeGet: 'Get Free',
    tipTitle: 'Notice',
    confirm: 'OK',
    myOrders: 'My Orders',
    myOrdersDesc: 'Start creating now',
    couponCenter: 'Coupon Center',
    couponAvailable: ' available',
    inviteFriends: 'Invite Friends',
    feedback: 'Feedback',
    aboutUs: 'About Us',
    aboutUsTitle: 'About FlashPhoto',
    language: 'Language',
    privacyPolicy: 'Privacy Policy',
    confirmed: 'Agreed',
    version: 'FlashPhoto v1.1.0',

    // Feedback
    fb_pageTitle: 'Feedback',
    fb_historyTitle: 'My Feedback History',
    fb_addNew: 'New Feedback',
    fb_noRecord: 'No feedback yet',
    fb_noRecordTip: 'Create your first feedback!',
    fb_submitNow: 'Submit Now',
    fb_pending: 'Pending',
    fb_replied: 'Replied',
    fb_edit: 'Edit',
    fb_delete: 'Delete',
    fb_adminReply: 'Admin Reply:',
    fb_reward: 'coins',
    fb_submitTitle: 'Submit Feedback',
    fb_placeholder: 'Please describe your issue or suggestion in detail...',
    fb_addImage: 'Add Image',
    fb_submit: 'Submit',
    fb_submitting: 'Submitting...',
    fb_submitSuccess: 'Feedback submitted',
    fb_submitFailed: 'Submit failed, please retry',
    fb_deleteConfirm: 'Delete this feedback?',
    fb_deleteSuccess: 'Deleted',
    fb_deleteFailed: 'Delete failed',
    
    // Feedback submit page
    editFeedback: 'Edit Feedback',
    submitNewFeedback: 'Submit Feedback',
    feedbackPlaceholder: 'Please describe your issue or suggestion in detail...',
    uploadImageOptional: 'Upload Image (Optional)',
    contactOptional: 'Contact (Optional)',
    contactPlaceholder: 'Email or phone number',
    confirmEdit: 'Confirm Edit',
    submitFeedback: 'Submit',

    // Modals
    setNickname: 'Set Nickname',
    enterNickname: 'Enter nickname',
    nicknameSaved: 'Nickname saved',
    bindEmailTitle: 'Bind Email',
    enterEmail: 'Enter email address',
    verifyCode: 'Verification code',
    sendCode: 'Send Code',
    confirmBind: 'Confirm',
    emailBound: 'Email bound successfully',
    invalidEmail: 'Invalid email format',
    codeError: 'Invalid verification code',
    codeSent: 'Code sent',

    // Language Selection
    selectLanguage: 'Select Language',
    langZhCN: '简体中文',
    langEn: 'English',
    languageChanged: 'Language changed',

    // History
    generatingPhotos: ' photos generating...',
    allCompleted: 'All completed',
    historyTitle: 'My Photos',
    noHistory: 'No photos yet',
    goCreate: 'Create Now',
    generating: 'Generating',
    failed: 'Failed',
    retry: 'Retry',
    download: 'Download',
    delete: 'Delete',
    selectAll: 'All',
    batchDelete: 'Batch Delete',
    selected: 'Selected',
    items: ' items',
    // History page detailed
    hist_pageTitle: 'History',
    hist_pending: 'Processing',
    hist_taskCount: ' tasks',
    hist_idPhoto: 'ID Photo',
    // History page filter tabs
    hist_filterStatus: 'Status',
    hist_filterSource: 'Source',
    hist_filterType: 'Type',
    hist_statusAll: 'All',
    hist_statusPending: 'Processing',
    hist_statusDone: 'Completed',
    hist_statusFailed: 'Failed',
    hist_sourceAll: 'All',
    hist_sourceOriginal: 'Original',
    hist_sourceRemake: 'Remake',
    hist_filterAll: 'All',
    hist_filterIdPhoto: 'ID Photo',
    hist_filterOther: 'Other',
    // History page - Scene category names (for filter tabs)
    hist_sceneIdPhoto: 'ID Photo',
    hist_sceneProfessional: 'Professional',
    hist_scenePortrait: 'Portrait',
    hist_sceneFamily: 'Family',
    hist_scenePet: 'Pet',
    hist_sceneWedding: 'Wedding',
    hist_filterNoRecords: 'No records in this category',
    hist_viewAll: 'View All',
    hist_aiGenerating: 'Generating...',
    hist_failedTitle: 'Failed',
    hist_clearAll: 'Clear',
    hist_photos: ' photos',
    hist_cancel: 'Done',
    hist_select: 'Edit',
    hist_selectedCount: '',
    hist_unit: ' sel.',
    hist_email: 'Mail',
    hist_download: 'Save',
    hist_delete: 'Del',
    hist_noRecords: 'No records',
    hist_noRecordsTip: 'Create your first ID photo',
    hist_createNow: 'Create',
    hist_bindEmail: 'Bind Email',
    hist_bindEmailTip: 'Bind email to send photos to your inbox',
    hist_enterEmail: 'Enter email address',
    hist_verifyCode: 'Code',
    hist_sendCode: 'Send Code',
    hist_confirmBindSend: 'Bind & Send',
    hist_selectPhoto: 'Please select photos first',
    hist_sending: 'Sending...',
    hist_sentToEmail: 'Sent to email',
    hist_saving: 'Saving...',
    hist_savedPhotos: 'Saved',
    hist_successCount: 'Success: ',
    hist_failCount: 'Failed: ',
    hist_confirmDeleteTitle: 'Confirm Delete',
    hist_confirmDeletePhotos: 'Delete selected ',
    hist_confirmDeleteSuffix: ' photos?',
    hist_deleted: 'Deleted',
    hist_clearFailedTitle: 'Clear Failed Tasks',
    hist_clearFailedContent: 'Clear all ',
    hist_clearFailedSuffix: ' failed tasks?',
    hist_cleared: 'Cleared',
    hist_confirmDeleteOne: 'This cannot be undone. Delete?',
    hist_justNow: 'Just now',
    hist_minutesAgo: ' min ago',
    hist_hoursAgo: ' hr ago',
    hist_daysAgo: ' days ago',
    hist_month: '/',
    hist_day: '',
    hist_needAlbum: 'Album permission required',
    hist_saveFailed: 'Save failed',
    hist_savedToAlbum: 'Saved to album',
    hist_aiDisclaimer: 'Images below are AI-generated, for reference only, please verify carefully',
    hist_freeRetry: '1 free retry',
    hist_freeRetryTitle: 'Free Regeneration',
    hist_freeRetryConfirm: 'You have 1 free regeneration chance. Use it now?',
    hist_retrying: 'Regenerating...',
    hist_retryStarted: 'Regeneration started',
    hist_retrySuccess: 'Added to regeneration queue',
    hist_noRetryLeft: 'No free retries left',
    hist_imageNotFound: 'Original image expired',
    hist_cancelTaskTitle: 'Cancel Task',
    hist_cancelTaskContent: 'Are you sure to cancel this generating task?',
    hist_cancelTaskContentWithWarning: 'Are you sure to cancel this generating task?\n\nNote: Points consumed for user-cancelled tasks will not be refunded.',
    hist_taskCanceled: 'Canceled',
    hist_timeoutError: 'Generation timeout, please retry',
    hist_retryTitle: 'Regenerate',
    hist_retryConfirm: 'Regenerate with original settings?',
    hist_systemErrorRetryTitle: 'Free Regeneration',
    hist_systemErrorRetryConfirm: 'Generation failed due to system error. No points will be charged. Regenerate with original image and settings?',
    hist_noPrompt: 'Cannot remake: missing original configuration',
    // Share feature
    hist_sharePoster: 'Share Poster',
    hist_shareCouponTip: 'Get 10 coins for first share',
    hist_shareToFriend: 'Share to Friends',
    hist_savePoster: 'Save Poster',
    hist_shareCouponName: 'Share Reward',
    hist_couponGrantedTitle: 'Coins Received',
    hist_couponGrantedContent: 'You got 10 coins reward!',
    hist_posterShareTitle: 'I made a photo with FlashPhoto, amazing!',
    hist_posterDesc: 'AI Photo, One Click',
    hist_posterTip: 'Long press to try',
    hist_tryNow: 'Try Now',
    // Detail modal action buttons
    detail_share: 'Share',
    detail_remake: 'Remake',
    detail_save: 'Save',
    detail_delete: 'Delete',
    // Detail modal generation conditions title
    detail_conditions: 'Generation Settings',

    // Privacy Tip
    privacyTip: 'To protect your rights, please read and agree to the privacy policy before using upload, generate, and payment features.',
    viewAndAgree: 'View & Agree',
    notNow: 'Not Now',

    // About Us Page
    about_pageTitle: 'About Us',
    about_appName: 'FlashPhoto',
    about_slogan: 'Upload Once, Get Perfect Photos',
    about_intro_title: 'About',
    about_intro_content: 'FlashPhoto is an intelligent photo generation tool powered by advanced AI technology. We provide convenient, high-quality photo services for ID photos, portraits, family photos, pet portraits, wedding photos and more, allowing you to get professional-grade beautiful photos without leaving home.',
    about_features_title: 'Features',
    about_feature1_name: 'AI Beauty',
    about_feature1_desc: 'Smart skin optimization, natural smoothing, blemish removal',
    about_feature2_name: 'Multiple Scenes',
    about_feature2_desc: 'ID photos, portraits, family photos, pet photos, wedding photos and more',
    about_feature3_name: 'Pro Specs',
    about_feature3_desc: '1 inch, 2 inch, passport sizes to meet all document needs',
    about_feature4_name: 'Smart Outfit',
    about_feature4_desc: 'Massive outfit templates, one-click professional or casual looks',
    about_contact_title: 'Contact Us',
    about_email: 'Support Email',
    about_contact_tips: 'If you have any questions or suggestions, please contact us via email. We will reply within 24 hours.',
    about_copyright: '© 2026 Shanghai Xingmei Yuanzi Network Technology Studio (Sole Proprietorship). All rights reserved.',
    about_share_title: 'FlashPhoto - AI Photo Generation',
    copied: 'Copied',
    aboutContent: 'FlashPhoto is a professional AI photo generation tool that supports ID photos, portraits, family photos, and more, with smart beautification and outfit changing features.',

    // Feature in development
    featureInDev: 'Coming soon',

    // Avatar and nickname
    avatarUpdated: 'Avatar updated',
    pleaseEnterNickname: 'Enter nickname',
    nicknameSaved: 'Nickname saved',

    // Email binding
    pleaseEnterEmail: 'Enter email',
    emailFormatError: 'Invalid email',
    sending: 'Sending...',
    codeSent: 'Code sent',
    testTip: 'Test',
    testCodeContent: 'Code: {code}',
    pleaseEnterCode: 'Enter code',
    codeError: 'Invalid code',
    emailBindSuccess: 'Email bound',

    // Share
    shareTitle: 'FlashPhoto - AI ID Photos',
    historyShareTitle: 'I made an ID photo with FlashPhoto!',
    newUserWelcome: 'New user! Get ¥5 off',

    // Recharge Page
    recharge_title: 'Top Up Points',
    currentPoints: 'Current Points',
    selectPackage: 'Select Amount',
    pointsUnit: 'Points',
    customAmount: 'Custom Amount',
    enterAmount: 'Enter amount (1-10000)',
    rechargeTips: 'Notes',
    rechargeTip1: '¥1 = 10 Points',
    rechargeTip2: 'Larger amounts get bonus points',
    rechargeTip3: 'Points can be used for all services',
    rechargeTip4: 'Instant credit after payment',
    payAmount: 'Pay Amount',
    rechargeNow: 'Top Up Now',
    processing: 'Processing...',
    pleaseEnterValidAmount: 'Enter valid amount',
    pleaseSelectAmount: 'Select amount',
    testMode: 'Test Mode',
    testRechargeConfirm: 'Simulate ¥{amount} top-up, get {points} points?',
    rechargeSuccess: 'Top up success',
    rechargeFailed: 'Top up failed',
    paymentCancelled: 'Payment cancelled',
    paymentFailed: 'Payment failed',
    pleaseLogin: 'Please login first',
    iosPaymentNotice: 'iOS Payment Not Available',
    iosPaymentDesc: 'You can get points through:',
    iosPaymentTip1: 'Top up on Android device',
    iosPaymentTip2: 'Share the app with friends',
    iosPaymentTip3: 'Invite friends to register',
    iosPaymentModalContent: 'Please use an Android device to top up, or get points by sharing or inviting friends',
    iKnow: 'OK',

    // Points Record Page
    pointsRecord_title: 'Points History',
    pointsHistory: 'Points Record',
    noRecords: 'No records yet',
    pr_balance: 'Balance',
    pr_noMore: 'No more records',
    pr_loadFailed: 'Load failed',
    pr_newUser: 'New user bonus',
    pr_shareImage: 'Share image bonus',
    pr_inviteFriend: 'Invite friend bonus',
    pr_recharge: 'Top up',
    pr_testRecharge: 'Test top up',
    pr_virtualRecharge: 'Virtual top up',
    pr_consume: 'Spent',
    pr_adminAdjust: 'System adjustment',
    pr_refund: 'System refund',
    pr_generate: 'Generate photo',
    pr_systemGrant: 'System grant',
    pr_activityReward: 'Activity reward',

    // ID Photo Page
    fp_uploadPhoto: 'Upload Photo',
    fp_uploadTip: 'Max 3 photos, AI reference',
    fp_add: 'Add',
    fp_photoSpec: 'Photo Size',
    fp_oneInch: '1 inch',
    fp_twoInch: '2 inch',
    fp_smallOneInch: 'Small 1"',
    fp_bigOneInch: 'Large 1"',
    fp_beauty: 'Beauty',
    fp_beautyNone: 'Original',
    fp_beautyNoneDesc: 'Crop & change BG',
    fp_beautyNatural: 'Natural',
    fp_beautyNaturalDesc: 'Light smoothing',
    fp_beautyEnhanced: 'Enhanced',
    fp_beautyEnhancedDesc: 'Slim & brighten',
    fp_recommend: 'Recommended',
    fp_smartClothing: 'Smart Outfit',
    fp_male: 'Male',
    fp_female: 'Female',
    fp_noClothing: 'No change',
    fp_suitTie: 'Suit & Tie',
    fp_suit: 'Suit',
    fp_whiteShirt: 'White Shirt',
    fp_vNeck: 'V-Neck',
    fp_roundNeck: 'Round Neck',
    fp_shirt: 'Shirt',
    fp_bgColor: 'Background',
    fp_white: 'White',
    fp_blue: 'Blue',
    fp_darkBlue: 'Dark Blue',
    fp_red: 'Red',
    fp_gray: 'Gray',
    fp_darkGray: 'Dark Gray',
    fp_gradient: 'Gradient',
    fp_beige: 'Beige',
    fp_lightGreen: 'Light Green',
    fp_brown: 'Brown',
    fp_unit: '',
    fp_generateNow: 'Generate Now',
    fp_confirmPay: 'Confirm Payment',
    fp_generateQty: 'Quantity',
    fp_unitPrice: 'Unit Price',
    fp_perPhoto: '/photo',
    fp_subtotal: 'Subtotal',
    fp_coupon: 'Coupon',
    fp_available: ' available',
    fp_noCoupon: 'No coupon',
    fp_tips: 'Notice',
    fp_disclaimer: 'This is an AI real-time generation service. Payment will immediately consume computing resources. Due to instant service delivery, refunds are not supported after generation. Please verify your photos and settings before payment.',
    fp_shouldPay: 'Total: ',
    fp_saved: 'Saved',
    fp_confirmPayBtn: 'Confirm Payment',
    fp_pleaseUpload: 'Please upload a photo first',
    fp_addedToQueue: 'Added to queue',
    fp_photosGenerating: ' photos generating...',
    fp_reassurance: 'Feel free to switch pages',
    fp_completedTapToView: 'All done! Tap to view',
    fp_photosCompleted: ' photos completed',
    fp_generateComplete: ' ID photos completed, check history',
    fp_generateFailed: 'Generation failed, please retry',
    fp_confirmDelete: 'Confirm Delete',
    fp_confirmDeleteContent: 'Are you sure to delete this record?',
    fp_filteredFormats: 'Filtered unsupported formats (JPG/PNG only)',
    fp_sensitiveContent: 'Image content not acceptable',
    fp_sensitiveContentModal: 'Your uploaded image does not meet ID photo requirements (may contain sensitive content). Please try with a different photo. No charge was made.',
    fp_iKnow: 'OK',
    fp_noImage: 'No image received',
    fp_privacyModalTitle: 'Please Confirm Privacy Policy',
    fp_privacyModalContent: 'Before using payment features, you need to read and agree to our privacy policy. This mini program only collects necessary information when you actively operate, for ID photo generation services.',
    fp_viewPrivacy: 'View Privacy Policy',
    fp_agreeAndContinue: 'Agree & Continue',
    fp_privacyRequired: 'Please agree to the privacy policy first',
    fp_goAgree: 'Go Agree',
    fp_noCouponAvailable: 'No coupons available',
    fp_needAlbumPermission: 'Album permission required',
    fp_savedCount: 'Saved',
    fp_saveFailed: 'Save failed',
    fp_sceneResume: 'ID Photo',
    fp_scenePassport: 'Visa Photo',
    fp_sceneExam: 'Exam Photo',
    fp_sceneSocial: 'Social Security',
    fp_sceneStudent: 'Student ID',

    // Scene page extra translations
    missingSceneParam: 'Missing scene parameter',
    sceneNotExist: 'Scene does not exist',
    configLoadFailed: 'Failed to load config',
    checkingImage: 'Checking image...',
    pleaseAgreePrivacy: 'Please agree to policy first',
    pleaseCompleteAction: 'Please complete action first',
    scene: 'Scene',
    photo: 'Photo',
    userNotLoggedIn: 'User not logged in',
    deductFailed: 'Deduction failed',
    noAvailableImage: 'No available image',
    cannotReadImage: 'Cannot read image',
    downloadFailed: 'Download failed',
    points: 'Points',
    consumePoints: 'Points to use',
    currentBalance: 'Current balance',
    insufficientBalance: 'Insufficient balance, please top up',
    iosInsufficientBalance: 'Insufficient balance. Get points by inviting friends or sharing photos',
    goRecharge: 'Top Up',
    hist_generateComplete: 'Completed, tap to view',

    // Professional Photo Page
    pp_pageTitle: 'Professional Photo',
    pp_uploadPhoto: 'Upload Photo',
    pp_uploadTip: 'Max 3 photos, AI reference',
    pp_gender: 'Select Gender',
    pp_industry: 'Select Industry',
    pp_posture: 'Select Posture',
    pp_indTech: 'Tech & IT',
    pp_indFinance: 'Finance',
    pp_indEducation: 'Education',
    pp_indMedical: 'Medical',
    pp_indCreative: 'Creative',
    pp_indLegal: 'Legal Services',
    pp_indMarketing: 'Marketing',
    pp_indMedia: 'Media',
    pp_indAdmin: 'Administration',
    pp_indOther: 'Other',
    pp_profession: 'Select Profession',
    // Tech & IT Professions
    pp_profSoftwareEngineer: 'Software Engineer',
    pp_profProductManager: 'Product Manager',
    pp_profUIDesigner: 'UI Designer',
    pp_profDataAnalyst: 'Data Analyst',
    pp_profProjectManager: 'Project Manager',
    // Finance Professions
    pp_profBanker: 'Banker',
    pp_profInvestAdvisor: 'Investment Advisor',
    pp_profAccountant: 'Accountant',
    pp_profInsurance: 'Insurance Advisor',
    pp_profSecurities: 'Securities Professional',
    // Education Professions
    pp_profTeacher: 'Teacher',
    pp_profProfessor: 'Professor',
    pp_profTrainer: 'Corporate Trainer',
    pp_profCounselor: 'Education Counselor',
    // Medical Professions
    pp_profDoctor: 'Doctor',
    pp_profNurse: 'Nurse',
    pp_profPharmacist: 'Pharmacist',
    pp_profTherapist: 'Therapist',
    // Legal Professions
    pp_profLawyer: 'Lawyer',
    pp_profLegalConsultant: 'Legal Consultant',
    pp_profNotary: 'Notary',
    // Marketing Professions
    pp_profMarketingManager: 'Marketing Manager',
    pp_profSalesManager: 'Sales Manager',
    pp_profBrandPlanner: 'Brand Planner',
    pp_profPR: 'PR Specialist',
    // Media Professions
    pp_profJournalist: 'Journalist',
    pp_profEditor: 'Editor',
    pp_profHost: 'Host',
    pp_profVideoProducer: 'Video Producer',
    // Administration Professions
    pp_profHR: 'HR Manager',
    pp_profAdminManager: 'Admin Manager',
    pp_profExecutive: 'Executive',
    pp_profSecretary: 'Secretary',
    // Other Professions
    pp_profEntrepreneur: 'Entrepreneur',
    pp_profFreelancer: 'Freelancer',
    pp_profConsultant: 'Consultant',
    pp_profGeneral: 'Professional',
    pp_profOther: 'Other',
    pp_generateComplete: ' professional photos completed',
    pp_desc: 'Job Hunting, Business Card, Professional Image',
    professionalPhoto: 'Professional Photo',
    pp_darkBlue: 'Dark Blue',
    pp_darkGray: 'Dark Gray',
    pp_beige: 'Beige',
    pp_lightGreen: 'Light Green',
    pp_brown: 'Brown',
    pp_framing: 'Framing',
    pp_framingCloseup: 'Close-up',
    pp_framingHalfbody: 'Half Body',
    pp_framingThreequarter: '3/4 Body',
    pp_framingFullbody: 'Full Body',

    // Orders Page
    order_pageTitle: 'Orders',
    order_title: 'My Orders',
    order_id: 'Order ID',
    order_generateQty: 'Quantity',
    order_coupon: 'Coupon',
    order_actualPay: 'Paid',
    order_completed: 'Completed',
    order_pending: 'Processing',
    order_failed: 'Failed',
    order_noOrders: 'No orders yet',
    order_goPhoto: 'Take Photo',

    // Coupons Page
    coupon_pageTitle: 'My Coupons',
    coupon_newUser: 'New User Coupon',
    coupon_noThreshold: 'No minimum',
    coupon_available: 'Available',
    coupon_used: 'Used',
    coupon_expired: 'Expired',
    coupon_noAvailable: 'No available coupons',
    coupon_noUsed: 'No used coupons',
    coupon_noExpired: 'No expired coupons',
    coupon_useNow: 'Use Now',
    coupon_inviteToGet: 'Invite friends to get coupons',
    coupon_validUntil: 'Valid until',
    coupon_longTerm: 'No expiry',

    // Invite Page
    invite_pageTitle: 'Invite',
    invite_title: 'Invite Friends & Save',
    invite_desc: 'Invite 1 friend, both get 10 coins',
    invite_invited: 'Invited',
    invite_earned: 'Earned',
    invite_earnedPoints: 'Points Earned',
    invite_claimable: 'Claimable',
    invite_pending: 'Pending',
    invite_nextProgress: 'Next Coupon Progress',
    invite_person: '',
    invite_personUnit: '',
    invite_getCoupon: 'Get',
    invite_pendingClaim: ' coupons to claim',
    invite_claimNow: 'Claim Now',
    invite_claimedCount: 'Claimed',
    invite_continueInvite: ' coupons, keep inviting for more',
    invite_moreToGet: 'Invite ',
    invite_personToGet: ' more to get 1 coupon',
    invite_method: 'How to Invite',
    invite_step1: 'Share App',
    invite_step1Desc: 'Send to friend',
    invite_step2: 'Friend Opens',
    invite_step2Desc: 'Enter app',
    invite_step3: 'Register',
    invite_step3Desc: 'Both get rewards',
    invite_shareTip: 'Tap "..." at top right to share',
    invite_shareMiniProgram: 'Share App',
    invite_sendToFriend: 'Send to friend',
    invite_friendClick: 'Friend Opens',
    invite_enterMiniProgram: 'Enter app',
    invite_generatePhoto: 'Agree Privacy',
    invite_success: 'Success',
    invite_shareNow: 'Share with Friends',
    invite_rules: 'Rules',
    invite_rule1: 'Invite friends via your link',
    invite_rule2: 'Friend registers and agrees to privacy policy',
    invite_rule3: 'Both get 10 coins for each successful invite',
    invite_rule4: 'Coins can be used for all services',
    invite_records: 'Invite History',
    invite_friend: 'Friend',
    invite_shareTitle: 'FlashPhoto - AI Photos made easy! Sign up to get coins!',
    invite_noCouponToClaim: 'No coupons to claim',
    invite_couponClaimed: ' coupons received',
    invite_rewardCoupon: 'Invite Reward',
    invite_noThreshold: 'No minimum',
    invite_rewardTitle: 'Reward Details',
    invite_friendReward: 'Invite Friends to Register',
    invite_friendRewardDesc: 'Both get rewards when friend registers',
    invite_shareReward: 'Share Generated Photos',
    invite_shareRewardDesc: 'First share of poster, no daily limit!',

    // Privacy Policy Page
    privacy_pageTitle: 'Privacy',
    privacy_title: 'Privacy Policy',
    privacy_welcome: 'Welcome to FlashPhoto (hereinafter referred to as "we" or "us").',
    privacy_intro: 'We highly value the protection of your personal information and privacy. This Privacy Policy explains how we collect, use, store, and protect your personal information when you use our mini program services, as well as your related rights.',
    privacy_read_tip: 'Please carefully read and understand this Privacy Policy before using this mini program.',
    privacy_section1_title: '1. How We Collect and Use Your Personal Information',
    privacy_section1_intro: 'We only collect and use your personal information for the following lawful, legitimate, and necessary purposes.',
    privacy_s1_1_title: '1.1 Registration and Login',
    privacy_s1_1_desc: 'When you use WeChat authorization to log in to this mini program, we will collect the following information:',
    privacy_s1_1_item1: 'WeChat user unique identifier (openid)',
    privacy_s1_1_item2: 'unionid (if provided by WeChat)',
    privacy_s1_1_purpose: 'Purpose: For user identification, account creation, and login.',
    privacy_s1_1_note: 'We will not ask you to provide additional information such as phone numbers or ID numbers.',
    privacy_s1_2_title: '1.2 ID Photo Generation and Editing Services',
    privacy_s1_2_desc: 'When you use ID photo generation features, we will collect:',
    privacy_s1_2_item1: 'Original photos you actively upload',
    privacy_s1_2_item2: 'Generated ID photos',
    privacy_s1_2_purpose: 'Purpose: To complete AI ID photo generation, preview, download, and other functions you request.',
    privacy_s1_2_note: 'Your photos are only used for this service and will not be used for advertising, marketing, or model training.',
    privacy_s1_3_title: '1.3 Orders and Payments',
    privacy_s1_3_desc: 'When you make a payment, we will collect:',
    privacy_s1_3_item1: 'Order number',
    privacy_s1_3_item2: 'Transaction amount',
    privacy_s1_3_item3: 'Payment status',
    privacy_s1_3_purpose: 'Purpose: To complete payment, order confirmation, and after-sales service.',
    privacy_s1_3_note: 'Payments are processed through WeChat Pay. We do not obtain sensitive information such as your bank card number or password.',
    privacy_s1_4_title: '1.4 Customer Service and Feedback (if you actively use it)',
    privacy_s1_4_desc: 'When you contact customer service or submit feedback, we may collect:',
    privacy_s1_4_item1: 'Contact information you provide',
    privacy_s1_4_item2: 'Feedback content',
    privacy_s1_4_purpose: 'Purpose: To communicate with you, handle issues, and improve our services.',
    privacy_s1_5_title: '1.5 System Security and Operation',
    privacy_s1_5_desc: 'To ensure the secure operation of the mini program, we may collect:',
    privacy_s1_5_item1: 'IP address',
    privacy_s1_5_item2: 'Device model',
    privacy_s1_5_item3: 'Operating system version',
    privacy_s1_5_item4: 'Basic operation logs',
    privacy_s1_5_purpose: 'Purpose: For security protection, troubleshooting, and system stability.',
    privacy_section2_title: '2. How We Store and Protect Your Personal Information',
    privacy_section2_item1: 'We will retain your personal information for the minimum time necessary to complete the service.',
    privacy_section2_item2: 'After the retention period, relevant information will be deleted or anonymized.',
    privacy_section2_item3: 'We employ reasonable technical and management measures to protect your information from unauthorized access, disclosure, or misuse.',
    privacy_section3_title: '3. How We Share, Transfer, or Disclose Your Personal Information',
    privacy_s3_1_title: '3.1 Third-Party Services',
    privacy_s3_1_desc: 'To implement related functions, we may use the following third-party services:',
    privacy_s3_1_item1: 'WeChat Open Platform: For WeChat login and WeChat Pay',
    privacy_s3_1_item2: 'Cloud services/AI image processing services: For ID photo generation and image storage',
    privacy_s3_1_note: 'We only share information within the scope necessary to implement functions.',
    privacy_s3_2_title: '3.2 We will not:',
    privacy_s3_2_item1: 'Sell your personal information to unrelated third parties',
    privacy_s3_2_item2: 'Use your photos for advertising or marketing',
    privacy_s3_2_item3: 'Disclose your personal information without authorization',
    privacy_s3_2_note: 'Unless otherwise required by law or with your explicit consent.',
    privacy_section4_title: '4. Your Rights',
    privacy_section4_intro: 'You have the right to:',
    privacy_section4_item1: 'Query and correct your personal information',
    privacy_section4_item2: 'Delete your personal information (within the scope permitted by law)',
    privacy_section4_item3: 'Withdraw authorization (may affect some functions)',
    privacy_section4_contact: 'You can contact us through the customer service entrance in the mini program.',
    privacy_section5_title: '5. Protection of Minors',
    privacy_section5_content: 'If you are under 14 years old, please use this mini program with the consent and guidance of your guardian.',
    privacy_section6_title: '6. Updates to This Policy',
    privacy_section6_content: 'We may update this Privacy Policy from time to time. Updates will be displayed through the mini program.',
    privacy_section7_title: '7. Contact Us',
    privacy_section7_content: 'If you have any questions, comments, or suggestions about this Privacy Policy, please contact us through the customer service/feedback entrance in the mini program.',
    privacy_checkbox_text: 'I have read and agree to the above Privacy Policy',
    privacy_confirm_btn: 'Confirm',
    privacy_please_agree: 'Please check to agree first',
    privacy_confirmed_toast: 'Privacy Policy confirmed',
    privacy_share_title: 'FlashPhoto - Privacy Policy',

    // Terms of Service Page
    terms_pageTitle: 'Terms of Service',
    terms_title: 'Terms of Service',
    terms_welcome: 'Welcome to FlashPhoto (hereinafter referred to as "the Product" or "we").',
    terms_intro: 'Please read and fully understand all terms of this User Agreement before using this product. If you do not agree to any terms of this agreement, please do not use this product. Your use of this product indicates that you have read and agreed to this agreement.',
    terms_section1_title: '1. Service Description',
    terms_section1_content: 'This product is an AI-powered ID photo generation tool that provides photo capture, beautification, outfit change, and background change services.',
    terms_s1_item1: 'After uploading photos, users can choose different specifications, background colors, beauty levels, etc.',
    terms_s1_item2: 'AI will generate ID photos according to the parameters selected by users',
    terms_s1_item3: 'Generated photos can be downloaded or sent to email',
    terms_section2_title: '2. User Account',
    terms_section2_intro: 'You can use this product by logging in with WeChat authorization.',
    terms_s2_item1: 'You should keep your account information safe. You are responsible for any theft or information leakage caused by your own reasons',
    terms_s2_item2: 'You may not transfer or lend your account to others',
    terms_s2_item3: 'If you find your account being used illegally, notify us immediately',
    terms_section3_title: '3. User Conduct Standards',
    terms_section3_intro: 'When using this product, you should comply with the following standards:',
    terms_s3_item1: 'Do not upload photos with illegal, pornographic, violent or other inappropriate content',
    terms_s3_item2: 'Do not upload photos that infringe on others\' portrait rights or privacy',
    terms_s3_item3: 'Do not use generated photos for any illegal purposes',
    terms_s3_item4: 'Do not use this product for any activities that violate laws and regulations',
    terms_s3_item5: 'Do not interfere with or damage the normal operation of this product',
    terms_section4_title: '4. Points Rules & Paid Services',
    terms_section4_intro: 'This product uses "Points" as virtual service currency. Please read the following rules carefully:',
    terms_s4_item1: 'Points are virtual service tokens for this product, usable only within this mini program. They have no monetary value',
    terms_s4_item2: 'Ways to obtain Points: purchase (¥1 = 10 Points), invite friends, share photos, etc.',
    terms_s4_item3: 'Points can only be used within this mini program. Transfer, gift, withdrawal, or cash redemption is not supported',
    terms_s4_item4: 'Due to the nature of real-time AI generation, Points spent are considered service delivered and refunds are not supported',
    terms_s4_item5: 'If generation fails due to system issues, consumed Points will be automatically refunded',
    terms_s4_item6: 'If users actively cancel a generating task, consumed Points will not be refunded',
    terms_s4_item7: 'When account is deleted, remaining Points will be cleared and cannot be recovered. Please use them before deletion',
    terms_s4_item8: 'We reserve the right to adjust Points acquisition rules and prices as needed, with advance notice',
    terms_section5_title: '5. Intellectual Property',
    terms_section5_intro: 'About the intellectual property of this product:',
    terms_s5_item1: 'All content of this product (including but not limited to text, images, code, interface design, etc.) is owned by us',
    terms_s5_item2: 'Original photos uploaded by users remain the property of users',
    terms_s5_item3: 'Users have the right to use AI-generated ID photos for personal legal purposes',
    terms_s5_item4: 'Without authorization, users may not reverse engineer or decompile this product',
    terms_section6_title: '6. Disclaimer',
    terms_section6_intro: 'To the extent permitted by law, we are not responsible for:',
    terms_s6_item1: 'AI-generated photos are for reference only and may differ from real photos',
    terms_s6_item2: 'Service interruption or data loss due to force majeure or network failures',
    terms_s6_item3: 'Any consequences arising from users violating this agreement or related laws',
    terms_s6_item4: 'When using generated photos for specific scenarios (such as visa applications), users should verify compliance with specific requirements',
    terms_section7_title: '7. Agreement Modification',
    terms_section7_content: 'We reserve the right to modify this agreement as needed. Modified agreements will be published within the product. Your continued use of this product indicates acceptance of the modified agreement. If you do not agree, please stop using this product.',
    terms_section8_title: '8. Applicable Law and Dispute Resolution',
    terms_section8_content: 'The conclusion, execution, interpretation and dispute resolution of this agreement shall be governed by the laws of the People\'s Republic of China. In case of disputes, both parties should resolve them through friendly negotiation; if negotiation fails, either party may file a lawsuit with the competent court.',
    terms_section9_title: '9. Contact Us',
    terms_section9_content: 'If you have any questions about this agreement, you can contact us through the "Feedback" feature in the product.',
    terms_update_time: 'Last updated: January 2025',
    terms_share_title: 'FlashPhoto - Terms of Service',

    // New: User info modal
    userInfoModal_nicknameRequired: 'Please enter nickname',
    userInfoModal_setSuccess: 'Settings saved',
    userInfoModal_setFailed: 'Settings failed',

    // New: Feedback submit page
    feedbackSubmit_editTitle: 'Edit Feedback',
    feedbackSubmit_imageUploadFailed: 'Image upload failed',
    feedbackSubmit_contentRequired: 'Please enter feedback content',
    feedbackSubmit_sensitiveFiltered: 'Some sensitive content has been filtered',
    feedbackSubmit_contentReviewing: 'Reviewing content...',
    feedbackSubmit_imageUploading: 'Uploading image, please wait',
    feedbackSubmit_editSuccess: 'Edit successful',
    feedbackSubmit_submitSuccess: 'Submit successful',

    // New: Points record types
    pr_type_newUser: 'New user bonus',
    pr_type_shareImage: 'Share image bonus',
    pr_type_inviteFriend: 'Invite friend bonus',
    pr_type_recharge: 'Top up',
    pr_type_testRecharge: 'Test top up',
    pr_type_virtualRecharge: 'Virtual top up',
    pr_type_consume: 'Spent',
    pr_type_generatePhoto: 'Generate photo',
    pr_type_systemAdjust: 'System adjustment',
    pr_type_systemRefund: 'System refund',
    pr_type_systemGrant: 'System grant',
    pr_type_activityReward: 'Activity reward',

    // New: Mine page
    mine_changeAvatar: 'Change Avatar',
    mine_viewLargeImage: 'View Large',
    mine_uploadingAvatar: 'Uploading avatar...',
    mine_avatarUploadFailed: 'Avatar upload failed',
    mine_avatarUpdated: 'Avatar updated',
    mine_nicknameUpdated: 'Nickname updated',
    mine_nicknameRequired: 'Please enter nickname',
    mine_saveSuccess: 'Saved successfully',

    // New: Feedback page
    fb_title: 'Feedback',
    fb_deleteConfirmTitle: 'Notice',
    fb_deleteConfirmContent: 'Are you sure to delete this feedback?',
    fb_deleted: 'Deleted',
    fb_deleteFailed: 'Delete failed',

    // New: Orders page
    order_consumeTitle: 'Consumption Records',
    order_statusCompleted: 'Completed',
    order_photoGeneration: 'Photo Generation',
    order_unit: '',
    order_consume: 'Spent',
    order_pointsUnit: 'Points',
    order_loadingMore: 'Loading...',
    order_noMoreData: 'No more data',

    // New: Privacy modal
    privacyModal_signFailed: 'Sign failed',
    privacyModal_signFailedMessage: 'Failed to sign agreement, please check network and retry',

    // New: Global notifications
    app_networkDisconnected: 'Network disconnected',
    app_networkRestored: 'Network restored',

    // New: Common
    common_tip: 'Notice',
    common_networkError: 'Network error',
    common_loadFailed: 'Load failed',

    // Scene page - Generation progress stages
    progress_queued: 'Queued...',
    progress_deducting: 'Processing payment...',
    progress_uploading: 'Uploading...',
    progress_processing: 'AI processing...',
    progress_generating: 'Generating...',
    progress_enhancing: 'Enhancing...',
    progress_saving: 'Saving...',
    progress_done: 'Done',
    progress_retrying: 'Retrying ({retry}/3)...',

    // Scene page - Insufficient balance modal
    insufficientBalanceTitle: 'Insufficient Balance',
    needMorePoints: 'Need',
    howToEarnPoints: 'How to earn points:',
    earnTip1: 'Invite friends +50 pts/person',
    earnTip2: 'Share photos +10 pts/time',
    earnTip3: 'Top up ¥1=10 pts',

    // Scene page - Generation complete message
    photosGenerateComplete: '{count} photos generated',

    // Dice roller component
    dice_clickToRoll: 'Tap dice to roll',
    dice_rolling: 'Rolling...',
    dice_rollAgain: 'Roll again',
    dice_clickRoll: 'Tap to roll',
    dice_free: 'Free',
    dice_confirmTitle: 'Confirm Points Usage',
    dice_confirmDesc: 'This roll will cost',
    dice_currentBalance: 'Current balance',
    dice_insufficientPoints: 'Insufficient points'
  }
};

// 获取当前语言
function getCurrentLang() {
  return wx.getStorageSync('language') || 'zh-CN';
}

// 获取翻译文本
function t(key) {
  const lang = getCurrentLang();
  const langPack = languages[lang] || languages['zh-CN'];
  return langPack[key] || key;
}

// 获取当前语言的所有翻译
function getLangData() {
  const lang = getCurrentLang();
  return languages[lang] || languages['zh-CN'];
}

// 设置语言
function setLang(langCode) {
  const oldLang = wx.getStorageSync('language');
  wx.setStorageSync('language', langCode);

  // 语言变化时，通知预加载器清除缓存并重新加载
  if (oldLang !== langCode) {
    try {
      const preloader = require('./preloader');
      preloader.onLanguageChange();
    } catch (e) {
      // 预加载器可能未初始化，忽略错误
    }
  }
}

module.exports = {
  t,
  getLangData,
  getCurrentLang,
  setLang,
  languages
};
